//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis.Framework.Localization.Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlantis.Framework.Localization.Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data count=&quot;8&quot;&gt;
        ///	&lt;item catalog_countrySite=&quot;www&quot; marketID=&quot;en-US&quot; languageUrlSegment=&quot;en&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///	&lt;item catalog_countrySite=&quot;www&quot; marketID=&quot;es-US&quot; languageUrlSegment=&quot;es&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///  &lt;item catalog_countrySite=&quot;www&quot; marketID=&quot;qa-QA&quot; languageUrlSegment=&quot;qa-qa&quot; isActive=&quot;-1&quot; internalOnly=&quot;-1&quot; /&gt;
        ///  &lt;item catalog_countrySite=&quot;www&quot; marketID=&quot;qa-PS&quot; languageUrlSegment=&quot;qa-ps&quot; isActive=&quot;-1&quot; internalOnly=&quot;-1&quot; /&gt;
        ///	&lt;item catalog_countrySite=&quot;ca&quot; marketID=&quot;en-CA&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultCountrySiteMarketMappings {
            get {
                return ResourceManager.GetString("DefaultCountrySiteMarketMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data count=&quot;5&quot;&gt;
        ///	&lt;item catalog_countrySite=&quot;au&quot; catalog_priceGroupID=&quot;0&quot; countrySiteDescription=&quot;Australia&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; defaultMarketID=&quot;en-AU&quot; defaultCurrencyType=&quot;AUD&quot;/&gt;
        ///	&lt;item catalog_countrySite=&quot;ca&quot; catalog_priceGroupID=&quot;0&quot; countrySiteDescription=&quot;Canada&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; defaultMarketID=&quot;en-CA&quot; defaultCurrencyType=&quot;CAD&quot;/&gt;
        ///	&lt;item catalog_countrySite=&quot;in&quot; catalog_priceGroupID=&quot;0&quot; countrySiteDescription=&quot;India&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; defaultMarketID=&quot;en-IN&quot; de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultCountrySitesActive {
            get {
                return ResourceManager.GetString("DefaultCountrySitesActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data count=&quot;8&quot;&gt;
        ///	&lt;item marketID=&quot;en-US&quot; marketDescription=&quot;English - United States&quot; msCulture=&quot;en-US&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///	&lt;item marketID=&quot;es-US&quot; marketDescription=&quot;Spanish - United States&quot; msCulture=&quot;es-US&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///	&lt;item marketID=&quot;en-CA&quot; marketDescription=&quot;English - Canada&quot; msCulture=&quot;en-CA&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///	&lt;item marketID=&quot;en-GB&quot; marketDescription=&quot;English - United Kingdom&quot; msCulture=&quot;en-GB&quot; isActive=&quot;-1&quot; internalOnly=&quot;0&quot; /&gt;
        ///	&lt;item marketID= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultMarketsActive {
            get {
                return ResourceManager.GetString("DefaultMarketsActive", resourceCulture);
            }
        }
    }
}
