//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.ProductPackager.Impl.ProductPackage {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="fastball.Product")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductGroupandPackageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductPackagesByPackageIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsByProductGroupIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Atlantis.Framework.ProductPackager.Impl.Properties.Settings.Default.Atlantis_Framework_ProductPackager_Impl_ProductPackage_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductGroupandPackageDataCompletedEventHandler GetProductGroupandPackageDataCompleted;
        
        /// <remarks/>
        public event GetProductPackagesByPackageIDCompletedEventHandler GetProductPackagesByPackageIDCompleted;
        
        /// <remarks/>
        public event GetProductsByProductGroupIDCompletedEventHandler GetProductsByProductGroupIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("fastball.Product/GetProductGroupandPackageData", RequestNamespace="fastball.Product", ResponseNamespace="fastball.Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResultCode")]
        public int GetProductGroupandPackageData(string[] productGroupIds, string[] packageIds, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out ProductAndPackageData ProductGroupAndPackageData) {
            object[] results = this.Invoke("GetProductGroupandPackageData", new object[] {
                        productGroupIds,
                        packageIds});
            ProductGroupAndPackageData = ((ProductAndPackageData)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductGroupandPackageDataAsync(string[] productGroupIds, string[] packageIds) {
            this.GetProductGroupandPackageDataAsync(productGroupIds, packageIds, null);
        }
        
        /// <remarks/>
        public void GetProductGroupandPackageDataAsync(string[] productGroupIds, string[] packageIds, object userState) {
            if ((this.GetProductGroupandPackageDataOperationCompleted == null)) {
                this.GetProductGroupandPackageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductGroupandPackageDataOperationCompleted);
            }
            this.InvokeAsync("GetProductGroupandPackageData", new object[] {
                        productGroupIds,
                        packageIds}, this.GetProductGroupandPackageDataOperationCompleted, userState);
        }
        
        private void OnGetProductGroupandPackageDataOperationCompleted(object arg) {
            if ((this.GetProductGroupandPackageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductGroupandPackageDataCompleted(this, new GetProductGroupandPackageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("fastball.Product/GetProductPackagesByPackageID", RequestNamespace="fastball.Product", ResponseNamespace="fastball.Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResultCode")]
        public int GetProductPackagesByPackageID(string[] packageIds, out ProdPackages objProdPackages) {
            object[] results = this.Invoke("GetProductPackagesByPackageID", new object[] {
                        packageIds});
            objProdPackages = ((ProdPackages)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductPackagesByPackageIDAsync(string[] packageIds) {
            this.GetProductPackagesByPackageIDAsync(packageIds, null);
        }
        
        /// <remarks/>
        public void GetProductPackagesByPackageIDAsync(string[] packageIds, object userState) {
            if ((this.GetProductPackagesByPackageIDOperationCompleted == null)) {
                this.GetProductPackagesByPackageIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductPackagesByPackageIDOperationCompleted);
            }
            this.InvokeAsync("GetProductPackagesByPackageID", new object[] {
                        packageIds}, this.GetProductPackagesByPackageIDOperationCompleted, userState);
        }
        
        private void OnGetProductPackagesByPackageIDOperationCompleted(object arg) {
            if ((this.GetProductPackagesByPackageIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductPackagesByPackageIDCompleted(this, new GetProductPackagesByPackageIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("fastball.Product/GetProductsByProductGroupID", RequestNamespace="fastball.Product", ResponseNamespace="fastball.Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResultCode")]
        public int GetProductsByProductGroupID(string[] productGroupIds, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out ProductGroupData ProductGroupData) {
            object[] results = this.Invoke("GetProductsByProductGroupID", new object[] {
                        productGroupIds});
            ProductGroupData = ((ProductGroupData)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsByProductGroupIDAsync(string[] productGroupIds) {
            this.GetProductsByProductGroupIDAsync(productGroupIds, null);
        }
        
        /// <remarks/>
        public void GetProductsByProductGroupIDAsync(string[] productGroupIds, object userState) {
            if ((this.GetProductsByProductGroupIDOperationCompleted == null)) {
                this.GetProductsByProductGroupIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsByProductGroupIDOperationCompleted);
            }
            this.InvokeAsync("GetProductsByProductGroupID", new object[] {
                        productGroupIds}, this.GetProductsByProductGroupIDOperationCompleted, userState);
        }
        
        private void OnGetProductsByProductGroupIDOperationCompleted(object arg) {
            if ((this.GetProductsByProductGroupIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsByProductGroupIDCompleted(this, new GetProductsByProductGroupIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductAndPackageData {
        
        private ProductGroup[] prodGroupsField;
        
        private ProdPackages prodPackagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProdGroup")]
        public ProductGroup[] ProdGroups {
            get {
                return this.prodGroupsField;
            }
            set {
                this.prodGroupsField = value;
            }
        }
        
        /// <remarks/>
        public ProdPackages ProdPackages {
            get {
                return this.prodPackagesField;
            }
            set {
                this.prodPackagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroup {
        
        private ProductGroupAttribute[] attribsField;
        
        private ProductGroupProducts[] prodsField;
        
        private string prodGroupCodeField;
        
        private string nameField;
        
        private string groupTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attrib")]
        public ProductGroupAttribute[] Attribs {
            get {
                return this.attribsField;
            }
            set {
                this.attribsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Prod")]
        public ProductGroupProducts[] Prods {
            get {
                return this.prodsField;
            }
            set {
                this.prodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string prodGroupCode {
            get {
                return this.prodGroupCodeField;
            }
            set {
                this.prodGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupAttribute {
        
        private ProductGroupAttribValue[] attribValsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttribVal")]
        public ProductGroupAttribValue[] AttribVals {
            get {
                return this.attribValsField;
            }
            set {
                this.attribValsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupAttribValue {
        
        private ProductGroupAttributeProducts[] prodsField;
        
        private string idField;
        
        private string disporderField;
        
        private string defaultField;
        
        private string nameField;
        
        private string valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Prod")]
        public ProductGroupAttributeProducts[] Prods {
            get {
                return this.prodsField;
            }
            set {
                this.prodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disporder {
            get {
                return this.disporderField;
            }
            set {
                this.disporderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupAttributeProducts {
        
        private string pfidField;
        
        private string qtyField;
        
        private string disporderField;
        
        private string defaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disporder {
            get {
                return this.disporderField;
            }
            set {
                this.disporderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupData {
        
        private ProductGroup[] prodGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProdGroup")]
        public ProductGroup[] ProdGroups {
            get {
                return this.prodGroupsField;
            }
            set {
                this.prodGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class AddonChildProd {
        
        private string pfidField;
        
        private string qtyField;
        
        private string defaultField;
        
        private string disporderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disporder {
            get {
                return this.disporderField;
            }
            set {
                this.disporderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class AddonParentProd {
        
        private AddonChildProd[] childProdsField;
        
        private string pfidField;
        
        private string qtyField;
        
        private string addonrequiredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChildProd")]
        public AddonChildProd[] ChildProds {
            get {
                return this.childProdsField;
            }
            set {
                this.childProdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string addonrequired {
            get {
                return this.addonrequiredField;
            }
            set {
                this.addonrequiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class AddOnProdPackage {
        
        private AddonParentProd parentProdField;
        
        private string pkgidField;
        
        /// <remarks/>
        public AddonParentProd ParentProd {
            get {
                return this.parentProdField;
            }
            set {
                this.parentProdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pkgid {
            get {
                return this.pkgidField;
            }
            set {
                this.pkgidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class UpsellChildProd {
        
        private string pfidField;
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class UpsellParentProd {
        
        private UpsellChildProd[] childProdsField;
        
        private string pfidField;
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChildProd")]
        public UpsellChildProd[] ChildProds {
            get {
                return this.childProdsField;
            }
            set {
                this.childProdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class UpsellProdPackage {
        
        private UpsellParentProd parentProdField;
        
        private string pkgidField;
        
        /// <remarks/>
        public UpsellParentProd ParentProd {
            get {
                return this.parentProdField;
            }
            set {
                this.parentProdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pkgid {
            get {
                return this.pkgidField;
            }
            set {
                this.pkgidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class CartChildprod {
        
        private string pfidField;
        
        private string qtyField;
        
        private string childflagField;
        
        private string isfreeField;
        
        private string discountcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string childflag {
            get {
                return this.childflagField;
            }
            set {
                this.childflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isfree {
            get {
                return this.isfreeField;
            }
            set {
                this.isfreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string discountcode {
            get {
                return this.discountcodeField;
            }
            set {
                this.discountcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class CartParentProd {
        
        private CartChildprod[] childProdsField;
        
        private string pfidField;
        
        private string qtyField;
        
        private string parentflagField;
        
        private string discountcodeField;
        
        private string dispoverrideField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChildProd")]
        public CartChildprod[] ChildProds {
            get {
                return this.childProdsField;
            }
            set {
                this.childProdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentflag {
            get {
                return this.parentflagField;
            }
            set {
                this.parentflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string discountcode {
            get {
                return this.discountcodeField;
            }
            set {
                this.discountcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispoverride {
            get {
                return this.dispoverrideField;
            }
            set {
                this.dispoverrideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class CartProdPackage {
        
        private CartParentProd parentProdField;
        
        private string pkgidField;
        
        /// <remarks/>
        public CartParentProd ParentProd {
            get {
                return this.parentProdField;
            }
            set {
                this.parentProdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pkgid {
            get {
                return this.pkgidField;
            }
            set {
                this.pkgidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProdPackages {
        
        private CartProdPackage[] cartPackagesField;
        
        private UpsellProdPackage[] upsellPackagesField;
        
        private AddOnProdPackage[] addonPackagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CartPackage")]
        public CartProdPackage[] CartPackages {
            get {
                return this.cartPackagesField;
            }
            set {
                this.cartPackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UpsellPackage")]
        public UpsellProdPackage[] UpsellPackages {
            get {
                return this.upsellPackagesField;
            }
            set {
                this.upsellPackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AddonPackage")]
        public AddOnProdPackage[] AddonPackages {
            get {
                return this.addonPackagesField;
            }
            set {
                this.addonPackagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupPackage {
        
        private string pkgidField;
        
        private string pkgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pkgid {
            get {
                return this.pkgidField;
            }
            set {
                this.pkgidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pkgType {
            get {
                return this.pkgTypeField;
            }
            set {
                this.pkgTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fastball.Product")]
    public partial class ProductGroupProducts {
        
        private ProductGroupPackage[] pkgsField;
        
        private string pfidField;
        
        private string qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Pkg")]
        public ProductGroupPackage[] Pkgs {
            get {
                return this.pkgsField;
            }
            set {
                this.pkgsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pfid {
            get {
                return this.pfidField;
            }
            set {
                this.pfidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductGroupandPackageDataCompletedEventHandler(object sender, GetProductGroupandPackageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductGroupandPackageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductGroupandPackageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ProductAndPackageData ProductGroupAndPackageData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductAndPackageData)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductPackagesByPackageIDCompletedEventHandler(object sender, GetProductPackagesByPackageIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductPackagesByPackageIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductPackagesByPackageIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ProdPackages objProdPackages {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProdPackages)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductsByProductGroupIDCompletedEventHandler(object sender, GetProductsByProductGroupIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsByProductGroupIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsByProductGroupIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ProductGroupData ProductGroupData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductGroupData)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591