//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.WSTService.Impl.WSTServiceWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTServiceSoap", Namespace="http://starfield.websitetonight.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebServiceResultantBaseOfThemeResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebServiceResultantBaseOfResult))]
    public partial class WSTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LockWSTProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback LockWSTProjectExOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnLockWSTProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnLockWSTProjectExOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWSTProjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWSTProject1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStagingPublishLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsProjectDesignLockedOperationCompleted;
        
        private System.Threading.SendOrPostCallback ColorsetIndexUpperBoundOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllActiveWSTThemesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllActiveThemesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuickSetupThemesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveDaVinciThemesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveWSTThemesByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveThemesByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllWSTCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWSTHeaderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountExecCanAccessWSTAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTService() {
            this.Url = global::Atlantis.Framework.WSTService.Impl.Properties.Settings.Default.Atlantis_Framework_WSTService_Impl_WSTServiceWS_WSTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LockWSTProjectCompletedEventHandler LockWSTProjectCompleted;
        
        /// <remarks/>
        public event LockWSTProjectExCompletedEventHandler LockWSTProjectExCompleted;
        
        /// <remarks/>
        public event UnLockWSTProjectCompletedEventHandler UnLockWSTProjectCompleted;
        
        /// <remarks/>
        public event UnLockWSTProjectExCompletedEventHandler UnLockWSTProjectExCompleted;
        
        /// <remarks/>
        public event CreateWSTProjectCompletedEventHandler CreateWSTProjectCompleted;
        
        /// <remarks/>
        public event CreateWSTProject1CompletedEventHandler CreateWSTProject1Completed;
        
        /// <remarks/>
        public event GetStagingPublishLinkCompletedEventHandler GetStagingPublishLinkCompleted;
        
        /// <remarks/>
        public event IsProjectDesignLockedCompletedEventHandler IsProjectDesignLockedCompleted;
        
        /// <remarks/>
        public event ColorsetIndexUpperBoundCompletedEventHandler ColorsetIndexUpperBoundCompleted;
        
        /// <remarks/>
        public event GetAllActiveWSTThemesCompletedEventHandler GetAllActiveWSTThemesCompleted;
        
        /// <remarks/>
        public event GetAllActiveThemesCompletedEventHandler GetAllActiveThemesCompleted;
        
        /// <remarks/>
        public event GetQuickSetupThemesCompletedEventHandler GetQuickSetupThemesCompleted;
        
        /// <remarks/>
        public event GetActiveDaVinciThemesCompletedEventHandler GetActiveDaVinciThemesCompleted;
        
        /// <remarks/>
        public event GetActiveWSTThemesByCategoryCompletedEventHandler GetActiveWSTThemesByCategoryCompleted;
        
        /// <remarks/>
        public event GetActiveThemesByCategoryCompletedEventHandler GetActiveThemesByCategoryCompleted;
        
        /// <remarks/>
        public event GetAllCategoriesCompletedEventHandler GetAllCategoriesCompleted;
        
        /// <remarks/>
        public event GetAllWSTCategoriesCompletedEventHandler GetAllWSTCategoriesCompleted;
        
        /// <remarks/>
        public event GetWSTHeaderInfoCompletedEventHandler GetWSTHeaderInfoCompleted;
        
        /// <remarks/>
        public event AccountExecCanAccessWSTAccountCompletedEventHandler AccountExecCanAccessWSTAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/LockWSTProject", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LockOperationResult LockWSTProject(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId) {
            object[] results = this.Invoke("LockWSTProject", new object[] {
                        quoteId,
                        orionAccountUID,
                        lockedBy,
                        pfId});
            return ((LockOperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void LockWSTProjectAsync(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId) {
            this.LockWSTProjectAsync(quoteId, orionAccountUID, lockedBy, pfId, null);
        }
        
        /// <remarks/>
        public void LockWSTProjectAsync(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId, object userState) {
            if ((this.LockWSTProjectOperationCompleted == null)) {
                this.LockWSTProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockWSTProjectOperationCompleted);
            }
            this.InvokeAsync("LockWSTProject", new object[] {
                        quoteId,
                        orionAccountUID,
                        lockedBy,
                        pfId}, this.LockWSTProjectOperationCompleted, userState);
        }
        
        private void OnLockWSTProjectOperationCompleted(object arg) {
            if ((this.LockWSTProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockWSTProjectCompleted(this, new LockWSTProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/LockWSTProjectEx", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LockOperationResult LockWSTProjectEx(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId, bool backup) {
            object[] results = this.Invoke("LockWSTProjectEx", new object[] {
                        quoteId,
                        orionAccountUID,
                        lockedBy,
                        pfId,
                        backup});
            return ((LockOperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void LockWSTProjectExAsync(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId, bool backup) {
            this.LockWSTProjectExAsync(quoteId, orionAccountUID, lockedBy, pfId, backup, null);
        }
        
        /// <remarks/>
        public void LockWSTProjectExAsync(int quoteId, System.Guid orionAccountUID, string lockedBy, int pfId, bool backup, object userState) {
            if ((this.LockWSTProjectExOperationCompleted == null)) {
                this.LockWSTProjectExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockWSTProjectExOperationCompleted);
            }
            this.InvokeAsync("LockWSTProjectEx", new object[] {
                        quoteId,
                        orionAccountUID,
                        lockedBy,
                        pfId,
                        backup}, this.LockWSTProjectExOperationCompleted, userState);
        }
        
        private void OnLockWSTProjectExOperationCompleted(object arg) {
            if ((this.LockWSTProjectExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockWSTProjectExCompleted(this, new LockWSTProjectExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/UnLockWSTProject", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnlockOperationResult UnLockWSTProject(int quoteId, System.Guid orionAccountUID, string unLockedBy) {
            object[] results = this.Invoke("UnLockWSTProject", new object[] {
                        quoteId,
                        orionAccountUID,
                        unLockedBy});
            return ((UnlockOperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void UnLockWSTProjectAsync(int quoteId, System.Guid orionAccountUID, string unLockedBy) {
            this.UnLockWSTProjectAsync(quoteId, orionAccountUID, unLockedBy, null);
        }
        
        /// <remarks/>
        public void UnLockWSTProjectAsync(int quoteId, System.Guid orionAccountUID, string unLockedBy, object userState) {
            if ((this.UnLockWSTProjectOperationCompleted == null)) {
                this.UnLockWSTProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnLockWSTProjectOperationCompleted);
            }
            this.InvokeAsync("UnLockWSTProject", new object[] {
                        quoteId,
                        orionAccountUID,
                        unLockedBy}, this.UnLockWSTProjectOperationCompleted, userState);
        }
        
        private void OnUnLockWSTProjectOperationCompleted(object arg) {
            if ((this.UnLockWSTProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnLockWSTProjectCompleted(this, new UnLockWSTProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/UnLockWSTProjectEx", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnlockOperationResult UnLockWSTProjectEx(int quoteId, System.Guid orionAccountUID, string unLockedBy, bool backup) {
            object[] results = this.Invoke("UnLockWSTProjectEx", new object[] {
                        quoteId,
                        orionAccountUID,
                        unLockedBy,
                        backup});
            return ((UnlockOperationResult)(results[0]));
        }
        
        /// <remarks/>
        public void UnLockWSTProjectExAsync(int quoteId, System.Guid orionAccountUID, string unLockedBy, bool backup) {
            this.UnLockWSTProjectExAsync(quoteId, orionAccountUID, unLockedBy, backup, null);
        }
        
        /// <remarks/>
        public void UnLockWSTProjectExAsync(int quoteId, System.Guid orionAccountUID, string unLockedBy, bool backup, object userState) {
            if ((this.UnLockWSTProjectExOperationCompleted == null)) {
                this.UnLockWSTProjectExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnLockWSTProjectExOperationCompleted);
            }
            this.InvokeAsync("UnLockWSTProjectEx", new object[] {
                        quoteId,
                        orionAccountUID,
                        unLockedBy,
                        backup}, this.UnLockWSTProjectExOperationCompleted, userState);
        }
        
        private void OnUnLockWSTProjectExOperationCompleted(object arg) {
            if ((this.UnLockWSTProjectExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnLockWSTProjectExCompleted(this, new UnLockWSTProjectExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/CreateWSTProject_1", RequestElementName="CreateWSTProject_1", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="CreateWSTProject_1Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateWSTProject_1Result")]
        public bool CreateWSTProject(Project apgProject, out Resultant resultant) {
            object[] results = this.Invoke("CreateWSTProject", new object[] {
                        apgProject});
            resultant = ((Resultant)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWSTProjectAsync(Project apgProject) {
            this.CreateWSTProjectAsync(apgProject, null);
        }
        
        /// <remarks/>
        public void CreateWSTProjectAsync(Project apgProject, object userState) {
            if ((this.CreateWSTProjectOperationCompleted == null)) {
                this.CreateWSTProjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWSTProjectOperationCompleted);
            }
            this.InvokeAsync("CreateWSTProject", new object[] {
                        apgProject}, this.CreateWSTProjectOperationCompleted, userState);
        }
        
        private void OnCreateWSTProjectOperationCompleted(object arg) {
            if ((this.CreateWSTProjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWSTProjectCompleted(this, new CreateWSTProjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="CreateWSTProject1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/CreateWSTProject_2", RequestElementName="CreateWSTProject_2", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="CreateWSTProject_2Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateWSTProject_2Result")]
        public bool CreateWSTProject(string xmlProject, out Resultant resultant) {
            object[] results = this.Invoke("CreateWSTProject1", new object[] {
                        xmlProject});
            resultant = ((Resultant)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWSTProject1Async(string xmlProject) {
            this.CreateWSTProject1Async(xmlProject, null);
        }
        
        /// <remarks/>
        public void CreateWSTProject1Async(string xmlProject, object userState) {
            if ((this.CreateWSTProject1OperationCompleted == null)) {
                this.CreateWSTProject1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWSTProject1OperationCompleted);
            }
            this.InvokeAsync("CreateWSTProject1", new object[] {
                        xmlProject}, this.CreateWSTProject1OperationCompleted, userState);
        }
        
        private void OnCreateWSTProject1OperationCompleted(object arg) {
            if ((this.CreateWSTProject1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWSTProject1Completed(this, new CreateWSTProject1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetStagingPublishLink", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStagingPublishLink(System.Guid orionAccountUID) {
            object[] results = this.Invoke("GetStagingPublishLink", new object[] {
                        orionAccountUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStagingPublishLinkAsync(System.Guid orionAccountUID) {
            this.GetStagingPublishLinkAsync(orionAccountUID, null);
        }
        
        /// <remarks/>
        public void GetStagingPublishLinkAsync(System.Guid orionAccountUID, object userState) {
            if ((this.GetStagingPublishLinkOperationCompleted == null)) {
                this.GetStagingPublishLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStagingPublishLinkOperationCompleted);
            }
            this.InvokeAsync("GetStagingPublishLink", new object[] {
                        orionAccountUID}, this.GetStagingPublishLinkOperationCompleted, userState);
        }
        
        private void OnGetStagingPublishLinkOperationCompleted(object arg) {
            if ((this.GetStagingPublishLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStagingPublishLinkCompleted(this, new GetStagingPublishLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/IsProjectDesignLocked", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsProjectDesignLocked(System.Guid orionAccountUID) {
            object[] results = this.Invoke("IsProjectDesignLocked", new object[] {
                        orionAccountUID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsProjectDesignLockedAsync(System.Guid orionAccountUID) {
            this.IsProjectDesignLockedAsync(orionAccountUID, null);
        }
        
        /// <remarks/>
        public void IsProjectDesignLockedAsync(System.Guid orionAccountUID, object userState) {
            if ((this.IsProjectDesignLockedOperationCompleted == null)) {
                this.IsProjectDesignLockedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsProjectDesignLockedOperationCompleted);
            }
            this.InvokeAsync("IsProjectDesignLocked", new object[] {
                        orionAccountUID}, this.IsProjectDesignLockedOperationCompleted, userState);
        }
        
        private void OnIsProjectDesignLockedOperationCompleted(object arg) {
            if ((this.IsProjectDesignLockedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsProjectDesignLockedCompleted(this, new IsProjectDesignLockedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/ColorIndexUpperBound_1", RequestElementName="ColorIndexUpperBound_1", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="ColorIndexUpperBound_1Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ColorIndexUpperBound_1Result")]
        public int ColorsetIndexUpperBound(int themeID, out ThemeResultant resultant) {
            object[] results = this.Invoke("ColorsetIndexUpperBound", new object[] {
                        themeID});
            resultant = ((ThemeResultant)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ColorsetIndexUpperBoundAsync(int themeID) {
            this.ColorsetIndexUpperBoundAsync(themeID, null);
        }
        
        /// <remarks/>
        public void ColorsetIndexUpperBoundAsync(int themeID, object userState) {
            if ((this.ColorsetIndexUpperBoundOperationCompleted == null)) {
                this.ColorsetIndexUpperBoundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnColorsetIndexUpperBoundOperationCompleted);
            }
            this.InvokeAsync("ColorsetIndexUpperBound", new object[] {
                        themeID}, this.ColorsetIndexUpperBoundOperationCompleted, userState);
        }
        
        private void OnColorsetIndexUpperBoundOperationCompleted(object arg) {
            if ((this.ColorsetIndexUpperBoundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ColorsetIndexUpperBoundCompleted(this, new ColorsetIndexUpperBoundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetAllActiveWSTThemes", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThemeInfo[] GetAllActiveWSTThemes() {
            object[] results = this.Invoke("GetAllActiveWSTThemes", new object[0]);
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllActiveWSTThemesAsync() {
            this.GetAllActiveWSTThemesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllActiveWSTThemesAsync(object userState) {
            if ((this.GetAllActiveWSTThemesOperationCompleted == null)) {
                this.GetAllActiveWSTThemesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllActiveWSTThemesOperationCompleted);
            }
            this.InvokeAsync("GetAllActiveWSTThemes", new object[0], this.GetAllActiveWSTThemesOperationCompleted, userState);
        }
        
        private void OnGetAllActiveWSTThemesOperationCompleted(object arg) {
            if ((this.GetAllActiveWSTThemesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllActiveWSTThemesCompleted(this, new GetAllActiveWSTThemesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetAllActiveThemes_1", RequestElementName="GetAllActiveThemes_1", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="GetAllActiveThemes_1Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetAllActiveThemes_1Result")]
        public ThemeInfo[] GetAllActiveThemes(out ThemeResultant resultant) {
            object[] results = this.Invoke("GetAllActiveThemes", new object[0]);
            resultant = ((ThemeResultant)(results[1]));
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllActiveThemesAsync() {
            this.GetAllActiveThemesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllActiveThemesAsync(object userState) {
            if ((this.GetAllActiveThemesOperationCompleted == null)) {
                this.GetAllActiveThemesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllActiveThemesOperationCompleted);
            }
            this.InvokeAsync("GetAllActiveThemes", new object[0], this.GetAllActiveThemesOperationCompleted, userState);
        }
        
        private void OnGetAllActiveThemesOperationCompleted(object arg) {
            if ((this.GetAllActiveThemesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllActiveThemesCompleted(this, new GetAllActiveThemesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetQuickSetupThemes", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThemeInfo[] GetQuickSetupThemes(bool isXXXDomain) {
            object[] results = this.Invoke("GetQuickSetupThemes", new object[] {
                        isXXXDomain});
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetQuickSetupThemesAsync(bool isXXXDomain) {
            this.GetQuickSetupThemesAsync(isXXXDomain, null);
        }
        
        /// <remarks/>
        public void GetQuickSetupThemesAsync(bool isXXXDomain, object userState) {
            if ((this.GetQuickSetupThemesOperationCompleted == null)) {
                this.GetQuickSetupThemesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuickSetupThemesOperationCompleted);
            }
            this.InvokeAsync("GetQuickSetupThemes", new object[] {
                        isXXXDomain}, this.GetQuickSetupThemesOperationCompleted, userState);
        }
        
        private void OnGetQuickSetupThemesOperationCompleted(object arg) {
            if ((this.GetQuickSetupThemesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuickSetupThemesCompleted(this, new GetQuickSetupThemesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetActiveDaVinciThemes", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThemeInfo[] GetActiveDaVinciThemes(string shopperId, int resellerId, out ThemeResultant resultant) {
            object[] results = this.Invoke("GetActiveDaVinciThemes", new object[] {
                        shopperId,
                        resellerId});
            resultant = ((ThemeResultant)(results[1]));
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveDaVinciThemesAsync(string shopperId, int resellerId) {
            this.GetActiveDaVinciThemesAsync(shopperId, resellerId, null);
        }
        
        /// <remarks/>
        public void GetActiveDaVinciThemesAsync(string shopperId, int resellerId, object userState) {
            if ((this.GetActiveDaVinciThemesOperationCompleted == null)) {
                this.GetActiveDaVinciThemesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveDaVinciThemesOperationCompleted);
            }
            this.InvokeAsync("GetActiveDaVinciThemes", new object[] {
                        shopperId,
                        resellerId}, this.GetActiveDaVinciThemesOperationCompleted, userState);
        }
        
        private void OnGetActiveDaVinciThemesOperationCompleted(object arg) {
            if ((this.GetActiveDaVinciThemesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveDaVinciThemesCompleted(this, new GetActiveDaVinciThemesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetActiveWSTThemesByCategory", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThemeInfo[] GetActiveWSTThemesByCategory(int categoryId) {
            object[] results = this.Invoke("GetActiveWSTThemesByCategory", new object[] {
                        categoryId});
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveWSTThemesByCategoryAsync(int categoryId) {
            this.GetActiveWSTThemesByCategoryAsync(categoryId, null);
        }
        
        /// <remarks/>
        public void GetActiveWSTThemesByCategoryAsync(int categoryId, object userState) {
            if ((this.GetActiveWSTThemesByCategoryOperationCompleted == null)) {
                this.GetActiveWSTThemesByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveWSTThemesByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetActiveWSTThemesByCategory", new object[] {
                        categoryId}, this.GetActiveWSTThemesByCategoryOperationCompleted, userState);
        }
        
        private void OnGetActiveWSTThemesByCategoryOperationCompleted(object arg) {
            if ((this.GetActiveWSTThemesByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveWSTThemesByCategoryCompleted(this, new GetActiveWSTThemesByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetActiveThemesByCategory_1", RequestElementName="GetActiveThemesByCategory_1", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="GetActiveThemesByCategory_1Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetActiveThemesByCategory_1Result")]
        public ThemeInfo[] GetActiveThemesByCategory(int categoryID, out ThemeResultant resultant) {
            object[] results = this.Invoke("GetActiveThemesByCategory", new object[] {
                        categoryID});
            resultant = ((ThemeResultant)(results[1]));
            return ((ThemeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveThemesByCategoryAsync(int categoryID) {
            this.GetActiveThemesByCategoryAsync(categoryID, null);
        }
        
        /// <remarks/>
        public void GetActiveThemesByCategoryAsync(int categoryID, object userState) {
            if ((this.GetActiveThemesByCategoryOperationCompleted == null)) {
                this.GetActiveThemesByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveThemesByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetActiveThemesByCategory", new object[] {
                        categoryID}, this.GetActiveThemesByCategoryOperationCompleted, userState);
        }
        
        private void OnGetActiveThemesByCategoryOperationCompleted(object arg) {
            if ((this.GetActiveThemesByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveThemesByCategoryCompleted(this, new GetActiveThemesByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetAllCategories_1", RequestElementName="GetAllCategories_1", RequestNamespace="http://starfield.websitetonight.com/", ResponseElementName="GetAllCategories_1Response", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("GetAllCategories_1Result")]
        public CategoryInfo[] GetAllCategories(out ThemeResultant resultant) {
            object[] results = this.Invoke("GetAllCategories", new object[0]);
            resultant = ((ThemeResultant)(results[1]));
            return ((CategoryInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync() {
            this.GetAllCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync(object userState) {
            if ((this.GetAllCategoriesOperationCompleted == null)) {
                this.GetAllCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetAllCategories", new object[0], this.GetAllCategoriesOperationCompleted, userState);
        }
        
        private void OnGetAllCategoriesOperationCompleted(object arg) {
            if ((this.GetAllCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetAllWSTCategories", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoryInfo[] GetAllWSTCategories() {
            object[] results = this.Invoke("GetAllWSTCategories", new object[0]);
            return ((CategoryInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllWSTCategoriesAsync() {
            this.GetAllWSTCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllWSTCategoriesAsync(object userState) {
            if ((this.GetAllWSTCategoriesOperationCompleted == null)) {
                this.GetAllWSTCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllWSTCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetAllWSTCategories", new object[0], this.GetAllWSTCategoriesOperationCompleted, userState);
        }
        
        private void OnGetAllWSTCategoriesOperationCompleted(object arg) {
            if ((this.GetAllWSTCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllWSTCategoriesCompleted(this, new GetAllWSTCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/GetWSTHeaderInfo", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSTHeaderInfo GetWSTHeaderInfo() {
            object[] results = this.Invoke("GetWSTHeaderInfo", new object[0]);
            return ((WSTHeaderInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetWSTHeaderInfoAsync() {
            this.GetWSTHeaderInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetWSTHeaderInfoAsync(object userState) {
            if ((this.GetWSTHeaderInfoOperationCompleted == null)) {
                this.GetWSTHeaderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWSTHeaderInfoOperationCompleted);
            }
            this.InvokeAsync("GetWSTHeaderInfo", new object[0], this.GetWSTHeaderInfoOperationCompleted, userState);
        }
        
        private void OnGetWSTHeaderInfoOperationCompleted(object arg) {
            if ((this.GetWSTHeaderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWSTHeaderInfoCompleted(this, new GetWSTHeaderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://starfield.websitetonight.com/AccountExecCanAccessWSTAccount", RequestNamespace="http://starfield.websitetonight.com/", ResponseNamespace="http://starfield.websitetonight.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AECheckResult AccountExecCanAccessWSTAccount(string accountExecShopperId, string orionAccountUid) {
            object[] results = this.Invoke("AccountExecCanAccessWSTAccount", new object[] {
                        accountExecShopperId,
                        orionAccountUid});
            return ((AECheckResult)(results[0]));
        }
        
        /// <remarks/>
        public void AccountExecCanAccessWSTAccountAsync(string accountExecShopperId, string orionAccountUid) {
            this.AccountExecCanAccessWSTAccountAsync(accountExecShopperId, orionAccountUid, null);
        }
        
        /// <remarks/>
        public void AccountExecCanAccessWSTAccountAsync(string accountExecShopperId, string orionAccountUid, object userState) {
            if ((this.AccountExecCanAccessWSTAccountOperationCompleted == null)) {
                this.AccountExecCanAccessWSTAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountExecCanAccessWSTAccountOperationCompleted);
            }
            this.InvokeAsync("AccountExecCanAccessWSTAccount", new object[] {
                        accountExecShopperId,
                        orionAccountUid}, this.AccountExecCanAccessWSTAccountOperationCompleted, userState);
        }
        
        private void OnAccountExecCanAccessWSTAccountOperationCompleted(object arg) {
            if ((this.AccountExecCanAccessWSTAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountExecCanAccessWSTAccountCompleted(this, new AccountExecCanAccessWSTAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public enum LockOperationResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        ProjectNotFound,
        
        /// <remarks/>
        ProjectAlreadyLockedException,
        
        /// <remarks/>
        DesignBackupException,
        
        /// <remarks/>
        SetOrionAttributeException,
        
        /// <remarks/>
        GetCustomTemplateStatusException,
        
        /// <remarks/>
        CustomTemplatesNotUsedException,
        
        /// <remarks/>
        OrionAccountNotFoundException,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public enum UnlockOperationResult {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        ProjectNotFound,
        
        /// <remarks/>
        ProjectAlreadyUnlockedException,
        
        /// <remarks/>
        DesignBackupException,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class Project {
        
        private System.Guid orionUidField;
        
        private int themeIDField;
        
        private int colorsetIndexField;
        
        private string emailField;
        
        private string companyNameField;
        
        private Page[] pagesField;
        
        /// <remarks/>
        public System.Guid OrionUid {
            get {
                return this.orionUidField;
            }
            set {
                this.orionUidField = value;
            }
        }
        
        /// <remarks/>
        public int ThemeID {
            get {
                return this.themeIDField;
            }
            set {
                this.themeIDField = value;
            }
        }
        
        /// <remarks/>
        public int ColorsetIndex {
            get {
                return this.colorsetIndexField;
            }
            set {
                this.colorsetIndexField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public Page[] Pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class Page {
        
        private string pageLayoutIDField;
        
        private string browserTitleField;
        
        private string headingTitleField;
        
        private string buttonTitleField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PageLayoutID {
            get {
                return this.pageLayoutIDField;
            }
            set {
                this.pageLayoutIDField = value;
            }
        }
        
        /// <remarks/>
        public string BrowserTitle {
            get {
                return this.browserTitleField;
            }
            set {
                this.browserTitleField = value;
            }
        }
        
        /// <remarks/>
        public string HeadingTitle {
            get {
                return this.headingTitleField;
            }
            set {
                this.headingTitleField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonTitle {
            get {
                return this.buttonTitleField;
            }
            set {
                this.buttonTitleField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class AECheckResult {
        
        private bool accountExecCanAccessWSTAccountField;
        
        private AEResultCode resultCodeField;
        
        /// <remarks/>
        public bool AccountExecCanAccessWSTAccount {
            get {
                return this.accountExecCanAccessWSTAccountField;
            }
            set {
                this.accountExecCanAccessWSTAccountField = value;
            }
        }
        
        /// <remarks/>
        public AEResultCode ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public enum AEResultCode {
        
        /// <remarks/>
        APIStatusUnknown,
        
        /// <remarks/>
        APISuccess,
        
        /// <remarks/>
        APIError,
        
        /// <remarks/>
        AccountExecFeatureDisabled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class WSTHeaderInfo {
        
        private string versionField;
        
        private string newfeatureurlField;
        
        private string feedbackurlField;
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string newfeatureurl {
            get {
                return this.newfeatureurlField;
            }
            set {
                this.newfeatureurlField = value;
            }
        }
        
        /// <remarks/>
        public string feedbackurl {
            get {
                return this.feedbackurlField;
            }
            set {
                this.feedbackurlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class CategoryInfo {
        
        private int categoryIdField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class ThemeInfo {
        
        private string themeLocationField;
        
        private string themeNameField;
        
        private int themeIdField;
        
        private int categoryIdField;
        
        private string themeUrlField;
        
        private string themeThumbnailUrlField;
        
        /// <remarks/>
        public string ThemeLocation {
            get {
                return this.themeLocationField;
            }
            set {
                this.themeLocationField = value;
            }
        }
        
        /// <remarks/>
        public string ThemeName {
            get {
                return this.themeNameField;
            }
            set {
                this.themeNameField = value;
            }
        }
        
        /// <remarks/>
        public int ThemeId {
            get {
                return this.themeIdField;
            }
            set {
                this.themeIdField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string ThemeUrl {
            get {
                return this.themeUrlField;
            }
            set {
                this.themeUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ThemeThumbnailUrl {
            get {
                return this.themeThumbnailUrlField;
            }
            set {
                this.themeThumbnailUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThemeResultant))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public abstract partial class WebServiceResultantBaseOfThemeResult {
        
        private ThemeResult resultField;
        
        private string descriptionField;
        
        private string exceptionField;
        
        /// <remarks/>
        public ThemeResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public enum ThemeResult {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Exception,
        
        /// <remarks/>
        CategoryInvalid,
        
        /// <remarks/>
        ThemeInvalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class ThemeResultant : WebServiceResultantBaseOfThemeResult {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultant))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public abstract partial class WebServiceResultantBaseOfResult {
        
        private Result resultField;
        
        private string descriptionField;
        
        private string exceptionField;
        
        /// <remarks/>
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public enum Result {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Exception,
        
        /// <remarks/>
        PreviousSite,
        
        /// <remarks/>
        PreviousProject,
        
        /// <remarks/>
        PageLayoutInvalid,
        
        /// <remarks/>
        BrowserTitleNotSpecified,
        
        /// <remarks/>
        InvalidFileName,
        
        /// <remarks/>
        OrionUidInvalid,
        
        /// <remarks/>
        ColorsetIndexInvalid,
        
        /// <remarks/>
        CompanyNameInvalid,
        
        /// <remarks/>
        EmailInvalid,
        
        /// <remarks/>
        PagesToFew,
        
        /// <remarks/>
        ThemeIDInvalid,
        
        /// <remarks/>
        XmlProjectNotWellFormed,
        
        /// <remarks/>
        XmlProjectInvalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://starfield.websitetonight.com/")]
    public partial class Resultant : WebServiceResultantBaseOfResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LockWSTProjectCompletedEventHandler(object sender, LockWSTProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LockWSTProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LockWSTProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LockOperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LockOperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LockWSTProjectExCompletedEventHandler(object sender, LockWSTProjectExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LockWSTProjectExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LockWSTProjectExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LockOperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LockOperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UnLockWSTProjectCompletedEventHandler(object sender, UnLockWSTProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnLockWSTProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnLockWSTProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnlockOperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnlockOperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UnLockWSTProjectExCompletedEventHandler(object sender, UnLockWSTProjectExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnLockWSTProjectExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnLockWSTProjectExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnlockOperationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnlockOperationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateWSTProjectCompletedEventHandler(object sender, CreateWSTProjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWSTProjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWSTProjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Resultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateWSTProject1CompletedEventHandler(object sender, CreateWSTProject1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWSTProject1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWSTProject1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Resultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStagingPublishLinkCompletedEventHandler(object sender, GetStagingPublishLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStagingPublishLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStagingPublishLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsProjectDesignLockedCompletedEventHandler(object sender, IsProjectDesignLockedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsProjectDesignLockedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsProjectDesignLockedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ColorsetIndexUpperBoundCompletedEventHandler(object sender, ColorsetIndexUpperBoundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColorsetIndexUpperBoundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ColorsetIndexUpperBoundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ThemeResultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeResultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllActiveWSTThemesCompletedEventHandler(object sender, GetAllActiveWSTThemesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllActiveWSTThemesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllActiveWSTThemesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllActiveThemesCompletedEventHandler(object sender, GetAllActiveThemesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllActiveThemesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllActiveThemesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ThemeResultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeResultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetQuickSetupThemesCompletedEventHandler(object sender, GetQuickSetupThemesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQuickSetupThemesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuickSetupThemesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActiveDaVinciThemesCompletedEventHandler(object sender, GetActiveDaVinciThemesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveDaVinciThemesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveDaVinciThemesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ThemeResultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeResultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActiveWSTThemesByCategoryCompletedEventHandler(object sender, GetActiveWSTThemesByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveWSTThemesByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveWSTThemesByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActiveThemesByCategoryCompletedEventHandler(object sender, GetActiveThemesByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveThemesByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveThemesByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThemeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeInfo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ThemeResultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeResultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCategoriesCompletedEventHandler(object sender, GetAllCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoryInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoryInfo[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ThemeResultant resultant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThemeResultant)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllWSTCategoriesCompletedEventHandler(object sender, GetAllWSTCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllWSTCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllWSTCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoryInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoryInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWSTHeaderInfoCompletedEventHandler(object sender, GetWSTHeaderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWSTHeaderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWSTHeaderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSTHeaderInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSTHeaderInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AccountExecCanAccessWSTAccountCompletedEventHandler(object sender, AccountExecCanAccessWSTAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountExecCanAccessWSTAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountExecCanAccessWSTAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AECheckResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AECheckResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591