//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.OrionEvent.Impl.OrionEventWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EventQueueSoap", Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class EventQueue : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ReadEventQueueByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadEventQueueByType_PagedOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadEventQueue_INITOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadEventQueuebySubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertEventsExOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReAssignEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEventsByEventIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEventProcessDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSubscriberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfiguredListenersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EventQueue() {
            this.Url = global::Atlantis.Framework.OrionEvent.Impl.Properties.Settings.Default.Atlantis_Framework_OrionInsertEvent_Impl_OrionEventWS_EventQueue;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadEventQueueByTypeCompletedEventHandler ReadEventQueueByTypeCompleted;
        
        /// <remarks/>
        public event ReadEventQueueByType_PagedCompletedEventHandler ReadEventQueueByType_PagedCompleted;
        
        /// <remarks/>
        public event ReadEventQueue_INITCompletedEventHandler ReadEventQueue_INITCompleted;
        
        /// <remarks/>
        public event ReadEventQueuebySubscriberCompletedEventHandler ReadEventQueuebySubscriberCompleted;
        
        /// <remarks/>
        public event InsertEventsCompletedEventHandler InsertEventsCompleted;
        
        /// <remarks/>
        public event InsertEventsExCompletedEventHandler InsertEventsExCompleted;
        
        /// <remarks/>
        public event UpdateEventsCompletedEventHandler UpdateEventsCompleted;
        
        /// <remarks/>
        public event AssignEventsCompletedEventHandler AssignEventsCompleted;
        
        /// <remarks/>
        public event ReAssignEventsCompletedEventHandler ReAssignEventsCompleted;
        
        /// <remarks/>
        public event GetEventsByEventIdCompletedEventHandler GetEventsByEventIdCompleted;
        
        /// <remarks/>
        public event UpdateEventProcessDateCompletedEventHandler UpdateEventProcessDateCompleted;
        
        /// <remarks/>
        public event AddSubscriberCompletedEventHandler AddSubscriberCompleted;
        
        /// <remarks/>
        public event GetSubscribersCompletedEventHandler GetSubscribersCompleted;
        
        /// <remarks/>
        public event GetConfiguredListenersCompletedEventHandler GetConfiguredListenersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/ReadEventQueueByType", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReadEventQueueByType(string ApplicationName, string ServerName, string[] EventTypes, out Event[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("ReadEventQueueByType", new object[] {
                        ApplicationName,
                        ServerName,
                        EventTypes});
            Results = ((Event[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void ReadEventQueueByTypeAsync(string ApplicationName, string ServerName, string[] EventTypes) {
            this.ReadEventQueueByTypeAsync(ApplicationName, ServerName, EventTypes, null);
        }
        
        /// <remarks/>
        public void ReadEventQueueByTypeAsync(string ApplicationName, string ServerName, string[] EventTypes, object userState) {
            if ((this.ReadEventQueueByTypeOperationCompleted == null)) {
                this.ReadEventQueueByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEventQueueByTypeOperationCompleted);
            }
            this.InvokeAsync("ReadEventQueueByType", new object[] {
                        ApplicationName,
                        ServerName,
                        EventTypes}, this.ReadEventQueueByTypeOperationCompleted, userState);
        }
        
        private void OnReadEventQueueByTypeOperationCompleted(object arg) {
            if ((this.ReadEventQueueByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadEventQueueByTypeCompleted(this, new ReadEventQueueByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/ReadEventQueueByType_Paged", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReadEventQueueByType_Paged(string ApplicationName, string ServerName, string[] EventTypes, int PageSize, long EventIndex, out Event[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("ReadEventQueueByType_Paged", new object[] {
                        ApplicationName,
                        ServerName,
                        EventTypes,
                        PageSize,
                        EventIndex});
            Results = ((Event[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void ReadEventQueueByType_PagedAsync(string ApplicationName, string ServerName, string[] EventTypes, int PageSize, long EventIndex) {
            this.ReadEventQueueByType_PagedAsync(ApplicationName, ServerName, EventTypes, PageSize, EventIndex, null);
        }
        
        /// <remarks/>
        public void ReadEventQueueByType_PagedAsync(string ApplicationName, string ServerName, string[] EventTypes, int PageSize, long EventIndex, object userState) {
            if ((this.ReadEventQueueByType_PagedOperationCompleted == null)) {
                this.ReadEventQueueByType_PagedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEventQueueByType_PagedOperationCompleted);
            }
            this.InvokeAsync("ReadEventQueueByType_Paged", new object[] {
                        ApplicationName,
                        ServerName,
                        EventTypes,
                        PageSize,
                        EventIndex}, this.ReadEventQueueByType_PagedOperationCompleted, userState);
        }
        
        private void OnReadEventQueueByType_PagedOperationCompleted(object arg) {
            if ((this.ReadEventQueueByType_PagedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadEventQueueByType_PagedCompleted(this, new ReadEventQueueByType_PagedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/ReadEventQueue_INIT", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReadEventQueue_INIT(string[] EventTypes, int PageSize, long EventIndex, out Event[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("ReadEventQueue_INIT", new object[] {
                        EventTypes,
                        PageSize,
                        EventIndex});
            Results = ((Event[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void ReadEventQueue_INITAsync(string[] EventTypes, int PageSize, long EventIndex) {
            this.ReadEventQueue_INITAsync(EventTypes, PageSize, EventIndex, null);
        }
        
        /// <remarks/>
        public void ReadEventQueue_INITAsync(string[] EventTypes, int PageSize, long EventIndex, object userState) {
            if ((this.ReadEventQueue_INITOperationCompleted == null)) {
                this.ReadEventQueue_INITOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEventQueue_INITOperationCompleted);
            }
            this.InvokeAsync("ReadEventQueue_INIT", new object[] {
                        EventTypes,
                        PageSize,
                        EventIndex}, this.ReadEventQueue_INITOperationCompleted, userState);
        }
        
        private void OnReadEventQueue_INITOperationCompleted(object arg) {
            if ((this.ReadEventQueue_INITCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadEventQueue_INITCompleted(this, new ReadEventQueue_INITCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/ReadEventQueuebySubscriber", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReadEventQueuebySubscriber(string Subscriber, int PageSize, long EventIndex, out Event[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("ReadEventQueuebySubscriber", new object[] {
                        Subscriber,
                        PageSize,
                        EventIndex});
            Results = ((Event[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void ReadEventQueuebySubscriberAsync(string Subscriber, int PageSize, long EventIndex) {
            this.ReadEventQueuebySubscriberAsync(Subscriber, PageSize, EventIndex, null);
        }
        
        /// <remarks/>
        public void ReadEventQueuebySubscriberAsync(string Subscriber, int PageSize, long EventIndex, object userState) {
            if ((this.ReadEventQueuebySubscriberOperationCompleted == null)) {
                this.ReadEventQueuebySubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEventQueuebySubscriberOperationCompleted);
            }
            this.InvokeAsync("ReadEventQueuebySubscriber", new object[] {
                        Subscriber,
                        PageSize,
                        EventIndex}, this.ReadEventQueuebySubscriberOperationCompleted, userState);
        }
        
        private void OnReadEventQueuebySubscriberOperationCompleted(object arg) {
            if ((this.ReadEventQueuebySubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadEventQueuebySubscriberCompleted(this, new ReadEventQueuebySubscriberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/InsertEvents", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertEvents(Event[] Events, out string[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("InsertEvents", new object[] {
                        Events});
            Results = ((string[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void InsertEventsAsync(Event[] Events) {
            this.InsertEventsAsync(Events, null);
        }
        
        /// <remarks/>
        public void InsertEventsAsync(Event[] Events, object userState) {
            if ((this.InsertEventsOperationCompleted == null)) {
                this.InsertEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertEventsOperationCompleted);
            }
            this.InvokeAsync("InsertEvents", new object[] {
                        Events}, this.InsertEventsOperationCompleted, userState);
        }
        
        private void OnInsertEventsOperationCompleted(object arg) {
            if ((this.InsertEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertEventsCompleted(this, new InsertEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/InsertEventsEx", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertEventsEx(Event[] Events, out EventId[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("InsertEventsEx", new object[] {
                        Events});
            Results = ((EventId[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void InsertEventsExAsync(Event[] Events) {
            this.InsertEventsExAsync(Events, null);
        }
        
        /// <remarks/>
        public void InsertEventsExAsync(Event[] Events, object userState) {
            if ((this.InsertEventsExOperationCompleted == null)) {
                this.InsertEventsExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertEventsExOperationCompleted);
            }
            this.InvokeAsync("InsertEventsEx", new object[] {
                        Events}, this.InsertEventsExOperationCompleted, userState);
        }
        
        private void OnInsertEventsExOperationCompleted(object arg) {
            if ((this.InsertEventsExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertEventsExCompleted(this, new InsertEventsExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/UpdateEvents", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateEvents(EventUpdate[] Events, out string[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("UpdateEvents", new object[] {
                        Events});
            Results = ((string[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void UpdateEventsAsync(EventUpdate[] Events) {
            this.UpdateEventsAsync(Events, null);
        }
        
        /// <remarks/>
        public void UpdateEventsAsync(EventUpdate[] Events, object userState) {
            if ((this.UpdateEventsOperationCompleted == null)) {
                this.UpdateEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEventsOperationCompleted);
            }
            this.InvokeAsync("UpdateEvents", new object[] {
                        Events}, this.UpdateEventsOperationCompleted, userState);
        }
        
        private void OnUpdateEventsOperationCompleted(object arg) {
            if ((this.UpdateEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEventsCompleted(this, new UpdateEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/AssignEvents", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AssignEvents(System.Guid[] EventUID, string[] Subscriber, out string[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("AssignEvents", new object[] {
                        EventUID,
                        Subscriber});
            Results = ((string[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void AssignEventsAsync(System.Guid[] EventUID, string[] Subscriber) {
            this.AssignEventsAsync(EventUID, Subscriber, null);
        }
        
        /// <remarks/>
        public void AssignEventsAsync(System.Guid[] EventUID, string[] Subscriber, object userState) {
            if ((this.AssignEventsOperationCompleted == null)) {
                this.AssignEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignEventsOperationCompleted);
            }
            this.InvokeAsync("AssignEvents", new object[] {
                        EventUID,
                        Subscriber}, this.AssignEventsOperationCompleted, userState);
        }
        
        private void OnAssignEventsOperationCompleted(object arg) {
            if ((this.AssignEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignEventsCompleted(this, new AssignEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/ReAssignEvents", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReAssignEvents(System.Guid[] EventUID, string[] Subscriber, out string[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("ReAssignEvents", new object[] {
                        EventUID,
                        Subscriber});
            Results = ((string[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void ReAssignEventsAsync(System.Guid[] EventUID, string[] Subscriber) {
            this.ReAssignEventsAsync(EventUID, Subscriber, null);
        }
        
        /// <remarks/>
        public void ReAssignEventsAsync(System.Guid[] EventUID, string[] Subscriber, object userState) {
            if ((this.ReAssignEventsOperationCompleted == null)) {
                this.ReAssignEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReAssignEventsOperationCompleted);
            }
            this.InvokeAsync("ReAssignEvents", new object[] {
                        EventUID,
                        Subscriber}, this.ReAssignEventsOperationCompleted, userState);
        }
        
        private void OnReAssignEventsOperationCompleted(object arg) {
            if ((this.ReAssignEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReAssignEventsCompleted(this, new ReAssignEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/GetEventsByEventId", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetEventsByEventId(int EventId, out Event[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("GetEventsByEventId", new object[] {
                        EventId});
            Results = ((Event[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void GetEventsByEventIdAsync(int EventId) {
            this.GetEventsByEventIdAsync(EventId, null);
        }
        
        /// <remarks/>
        public void GetEventsByEventIdAsync(int EventId, object userState) {
            if ((this.GetEventsByEventIdOperationCompleted == null)) {
                this.GetEventsByEventIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventsByEventIdOperationCompleted);
            }
            this.InvokeAsync("GetEventsByEventId", new object[] {
                        EventId}, this.GetEventsByEventIdOperationCompleted, userState);
        }
        
        private void OnGetEventsByEventIdOperationCompleted(object arg) {
            if ((this.GetEventsByEventIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEventsByEventIdCompleted(this, new GetEventsByEventIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/UpdateEventProcessDate", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateEventProcessDate(Event[] Events, out string[] Results, out string[] Errors) {
            object[] results1 = this.Invoke("UpdateEventProcessDate", new object[] {
                        Events});
            Results = ((string[])(results1[1]));
            Errors = ((string[])(results1[2]));
            return ((int)(results1[0]));
        }
        
        /// <remarks/>
        public void UpdateEventProcessDateAsync(Event[] Events) {
            this.UpdateEventProcessDateAsync(Events, null);
        }
        
        /// <remarks/>
        public void UpdateEventProcessDateAsync(Event[] Events, object userState) {
            if ((this.UpdateEventProcessDateOperationCompleted == null)) {
                this.UpdateEventProcessDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEventProcessDateOperationCompleted);
            }
            this.InvokeAsync("UpdateEventProcessDate", new object[] {
                        Events}, this.UpdateEventProcessDateOperationCompleted, userState);
        }
        
        private void OnUpdateEventProcessDateOperationCompleted(object arg) {
            if ((this.UpdateEventProcessDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEventProcessDateCompleted(this, new UpdateEventProcessDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/AddSubscriber", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddSubscriber(string SubscriberName) {
            this.Invoke("AddSubscriber", new object[] {
                        SubscriberName});
        }
        
        /// <remarks/>
        public void AddSubscriberAsync(string SubscriberName) {
            this.AddSubscriberAsync(SubscriberName, null);
        }
        
        /// <remarks/>
        public void AddSubscriberAsync(string SubscriberName, object userState) {
            if ((this.AddSubscriberOperationCompleted == null)) {
                this.AddSubscriberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSubscriberOperationCompleted);
            }
            this.InvokeAsync("AddSubscriber", new object[] {
                        SubscriberName}, this.AddSubscriberOperationCompleted, userState);
        }
        
        private void OnAddSubscriberOperationCompleted(object arg) {
            if ((this.AddSubscriberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSubscriberCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/GetSubscribers", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Subscribers")]
        public Subscriber[] GetSubscribers(string SubscriberName, bool AllowPartialMatch) {
            object[] results = this.Invoke("GetSubscribers", new object[] {
                        SubscriberName,
                        AllowPartialMatch});
            return ((Subscriber[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubscribersAsync(string SubscriberName, bool AllowPartialMatch) {
            this.GetSubscribersAsync(SubscriberName, AllowPartialMatch, null);
        }
        
        /// <remarks/>
        public void GetSubscribersAsync(string SubscriberName, bool AllowPartialMatch, object userState) {
            if ((this.GetSubscribersOperationCompleted == null)) {
                this.GetSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubscribersOperationCompleted);
            }
            this.InvokeAsync("GetSubscribers", new object[] {
                        SubscriberName,
                        AllowPartialMatch}, this.GetSubscribersOperationCompleted, userState);
        }
        
        private void OnGetSubscribersOperationCompleted(object arg) {
            if ((this.GetSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubscribersCompleted(this, new GetSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://alpha.orion.dev.starfieldtech.com/GetConfiguredListeners", RequestNamespace="http://alpha.orion.dev.starfieldtech.com", ResponseNamespace="http://alpha.orion.dev.starfieldtech.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Listeners")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Name")]
        public string[] GetConfiguredListeners(string EventType) {
            object[] results = this.Invoke("GetConfiguredListeners", new object[] {
                        EventType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConfiguredListenersAsync(string EventType) {
            this.GetConfiguredListenersAsync(EventType, null);
        }
        
        /// <remarks/>
        public void GetConfiguredListenersAsync(string EventType, object userState) {
            if ((this.GetConfiguredListenersOperationCompleted == null)) {
                this.GetConfiguredListenersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfiguredListenersOperationCompleted);
            }
            this.InvokeAsync("GetConfiguredListeners", new object[] {
                        EventType}, this.GetConfiguredListenersOperationCompleted, userState);
        }
        
        private void OnGetConfiguredListenersOperationCompleted(object arg) {
            if ((this.GetConfiguredListenersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfiguredListenersCompleted(this, new GetConfiguredListenersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class Subscriber {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class EventUpdate {
        
        private System.Guid uIDField;
        
        private string statusField;
        
        private string auditMessageField;
        
        /// <remarks/>
        public System.Guid UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string AuditMessage {
            get {
                return this.auditMessageField;
            }
            set {
                this.auditMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class EventId {
        
        private System.Guid uidField;
        
        private long idField;
        
        /// <remarks/>
        public System.Guid Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class EventAuditItem {
        
        private long idField;
        
        private long eventIDField;
        
        private int statusIDField;
        
        private string statusDescriptionField;
        
        private string messageField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateModifiedField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        public int StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class AccountInternalData {
        
        private string itemNameField;
        
        private string itemValueField;
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemValue {
            get {
                return this.itemValueField;
            }
            set {
                this.itemValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class AccountQuotaDetail {
        
        private string accountAttributeNameField;
        
        private string quotaTypeField;
        
        private float quotaUsageField;
        
        private System.DateTime quotaBeginPeriodField;
        
        private System.DateTime quotaEndPeriodField;
        
        /// <remarks/>
        public string AccountAttributeName {
            get {
                return this.accountAttributeNameField;
            }
            set {
                this.accountAttributeNameField = value;
            }
        }
        
        /// <remarks/>
        public string QuotaType {
            get {
                return this.quotaTypeField;
            }
            set {
                this.quotaTypeField = value;
            }
        }
        
        /// <remarks/>
        public float QuotaUsage {
            get {
                return this.quotaUsageField;
            }
            set {
                this.quotaUsageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuotaBeginPeriod {
            get {
                return this.quotaBeginPeriodField;
            }
            set {
                this.quotaBeginPeriodField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuotaEndPeriod {
            get {
                return this.quotaEndPeriodField;
            }
            set {
                this.quotaEndPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class AccountQuota {
        
        private ObjectType objTypeField;
        
        private string objectUidField;
        
        private string quotaTypeField;
        
        private float quotaUsageField;
        
        private System.DateTime quotaBeginPeriodField;
        
        private System.DateTime quotaEndPeriodField;
        
        private AccountQuotaDetail[] detailsField;
        
        /// <remarks/>
        public ObjectType objType {
            get {
                return this.objTypeField;
            }
            set {
                this.objTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectUid {
            get {
                return this.objectUidField;
            }
            set {
                this.objectUidField = value;
            }
        }
        
        /// <remarks/>
        public string QuotaType {
            get {
                return this.quotaTypeField;
            }
            set {
                this.quotaTypeField = value;
            }
        }
        
        /// <remarks/>
        public float QuotaUsage {
            get {
                return this.quotaUsageField;
            }
            set {
                this.quotaUsageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuotaBeginPeriod {
            get {
                return this.quotaBeginPeriodField;
            }
            set {
                this.quotaBeginPeriodField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuotaEndPeriod {
            get {
                return this.quotaEndPeriodField;
            }
            set {
                this.quotaEndPeriodField = value;
            }
        }
        
        /// <remarks/>
        public AccountQuotaDetail[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public enum ObjectType {
        
        /// <remarks/>
        ACCOUNT,
        
        /// <remarks/>
        ATTRIBUTE,
        
        /// <remarks/>
        ELEMENT,
        
        /// <remarks/>
        SERVER,
        
        /// <remarks/>
        RESELLER,
        
        /// <remarks/>
        APPLICATION,
        
        /// <remarks/>
        PRODUCT,
        
        /// <remarks/>
        PRODUCT_ATTRIBUTE,
        
        /// <remarks/>
        PRODUCT_ATTRIBUTE_ELEMENT,
        
        /// <remarks/>
        ACCOUNT_ATTRIBUTE,
        
        /// <remarks/>
        ACCOUNT_ATTRIBUTE_ELEMENT,
        
        /// <remarks/>
        MODIFIED_ELEMENT,
        
        /// <remarks/>
        NEW_ATTRIBUTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class AccountElement {
        
        private string nameField;
        
        private string valueField;
        
        private int elementIdField;
        
        private string elementUidField;
        
        private string productAttributeElementUidField;
        
        private string statusField;
        
        private string displayStatusField;
        
        private int readOnlyField;
        
        private int canBeModifiedField;
        
        private AccountElement[] childElementsField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public int ElementId {
            get {
                return this.elementIdField;
            }
            set {
                this.elementIdField = value;
            }
        }
        
        /// <remarks/>
        public string ElementUid {
            get {
                return this.elementUidField;
            }
            set {
                this.elementUidField = value;
            }
        }
        
        /// <remarks/>
        public string ProductAttributeElementUid {
            get {
                return this.productAttributeElementUidField;
            }
            set {
                this.productAttributeElementUidField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayStatus {
            get {
                return this.displayStatusField;
            }
            set {
                this.displayStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        public int CanBeModified {
            get {
                return this.canBeModifiedField;
            }
            set {
                this.canBeModifiedField = value;
            }
        }
        
        /// <remarks/>
        public AccountElement[] ChildElements {
            get {
                return this.childElementsField;
            }
            set {
                this.childElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class AccountAttribute {
        
        private int attributeIdField;
        
        private string attributeUidField;
        
        private string productAttributeUidField;
        
        private int isTemplateAttributeField;
        
        private string templateInternalNameField;
        
        private string nameField;
        
        private string statusField;
        
        private string displayStatusField;
        
        private int readOnlyField;
        
        private int canBeModifiedField;
        
        private AccountElement[] accountElementsField;
        
        /// <remarks/>
        public int AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
            }
        }
        
        /// <remarks/>
        public string AttributeUid {
            get {
                return this.attributeUidField;
            }
            set {
                this.attributeUidField = value;
            }
        }
        
        /// <remarks/>
        public string ProductAttributeUid {
            get {
                return this.productAttributeUidField;
            }
            set {
                this.productAttributeUidField = value;
            }
        }
        
        /// <remarks/>
        public int IsTemplateAttribute {
            get {
                return this.isTemplateAttributeField;
            }
            set {
                this.isTemplateAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string TemplateInternalName {
            get {
                return this.templateInternalNameField;
            }
            set {
                this.templateInternalNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayStatus {
            get {
                return this.displayStatusField;
            }
            set {
                this.displayStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        public int CanBeModified {
            get {
                return this.canBeModifiedField;
            }
            set {
                this.canBeModifiedField = value;
            }
        }
        
        /// <remarks/>
        public AccountElement[] AccountElements {
            get {
                return this.accountElementsField;
            }
            set {
                this.accountElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class Account {
        
        private string systemNamespaceField;
        
        private int resellerIdField;
        
        private string customerNumField;
        
        private string productNameField;
        
        private int productTemplateIdField;
        
        private string productTemplateNameField;
        
        private string productUidField;
        
        private int orionCustomerIdField;
        
        private int accountIdField;
        
        private string accountUidField;
        
        private string displayStatusField;
        
        private string statusField;
        
        private System.DateTime expireDateField;
        
        private int canBeModifiedField;
        
        private int isActiveField;
        
        private int isRemovedField;
        
        private AccountAttribute[] accountAttributesField;
        
        private AccountQuota[] quotasField;
        
        private AccountInternalData[] dataField;
        
        /// <remarks/>
        public string SystemNamespace {
            get {
                return this.systemNamespaceField;
            }
            set {
                this.systemNamespaceField = value;
            }
        }
        
        /// <remarks/>
        public int ResellerId {
            get {
                return this.resellerIdField;
            }
            set {
                this.resellerIdField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNum {
            get {
                return this.customerNumField;
            }
            set {
                this.customerNumField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int ProductTemplateId {
            get {
                return this.productTemplateIdField;
            }
            set {
                this.productTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductTemplateName {
            get {
                return this.productTemplateNameField;
            }
            set {
                this.productTemplateNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductUid {
            get {
                return this.productUidField;
            }
            set {
                this.productUidField = value;
            }
        }
        
        /// <remarks/>
        public int OrionCustomerId {
            get {
                return this.orionCustomerIdField;
            }
            set {
                this.orionCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public int AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountUid {
            get {
                return this.accountUidField;
            }
            set {
                this.accountUidField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayStatus {
            get {
                return this.displayStatusField;
            }
            set {
                this.displayStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        public int CanBeModified {
            get {
                return this.canBeModifiedField;
            }
            set {
                this.canBeModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public int IsRemoved {
            get {
                return this.isRemovedField;
            }
            set {
                this.isRemovedField = value;
            }
        }
        
        /// <remarks/>
        public AccountAttribute[] AccountAttributes {
            get {
                return this.accountAttributesField;
            }
            set {
                this.accountAttributesField = value;
            }
        }
        
        /// <remarks/>
        public AccountQuota[] Quotas {
            get {
                return this.quotasField;
            }
            set {
                this.quotasField = value;
            }
        }
        
        /// <remarks/>
        public AccountInternalData[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class EventItem {
        
        private long idField;
        
        private System.Guid uIDField;
        
        private System.Guid targetUIDField;
        
        private System.DateTime dateCreatedField;
        
        private string itemTypeField;
        
        private string itemTypeDescriptionField;
        
        private string objectTypeField;
        
        private string valueField;
        
        private string priorValueField;
        
        private Account detailsField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TargetUID {
            get {
                return this.targetUIDField;
            }
            set {
                this.targetUIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemTypeDescription {
            get {
                return this.itemTypeDescriptionField;
            }
            set {
                this.itemTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string PriorValue {
            get {
                return this.priorValueField;
            }
            set {
                this.priorValueField = value;
            }
        }
        
        /// <remarks/>
        public Account Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alpha.orion.dev.starfieldtech.com")]
    public partial class Event {
        
        private long idField;
        
        private System.Guid uIDField;
        
        private string auditMessageField;
        
        private string eventTypeField;
        
        private string eventTypeDescriptionField;
        
        private string requestorField;
        
        private string requestorDescriptionField;
        
        private string statusField;
        
        private string statusDescriptionField;
        
        private System.DateTime dateCreatedField;
        
        private System.DateTime dateModifiedField;
        
        private System.DateTime dateCompletedField;
        
        private System.DateTime processDateField;
        
        private EventItem[] eventItemsField;
        
        private EventAuditItem[] auditItemsField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string AuditMessage {
            get {
                return this.auditMessageField;
            }
            set {
                this.auditMessageField = value;
            }
        }
        
        /// <remarks/>
        public string EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EventTypeDescription {
            get {
                return this.eventTypeDescriptionField;
            }
            set {
                this.eventTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        public string RequestorDescription {
            get {
                return this.requestorDescriptionField;
            }
            set {
                this.requestorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCompleted {
            get {
                return this.dateCompletedField;
            }
            set {
                this.dateCompletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProcessDate {
            get {
                return this.processDateField;
            }
            set {
                this.processDateField = value;
            }
        }
        
        /// <remarks/>
        public EventItem[] EventItems {
            get {
                return this.eventItemsField;
            }
            set {
                this.eventItemsField = value;
            }
        }
        
        /// <remarks/>
        public EventAuditItem[] AuditItems {
            get {
                return this.auditItemsField;
            }
            set {
                this.auditItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadEventQueueByTypeCompletedEventHandler(object sender, ReadEventQueueByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadEventQueueByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadEventQueueByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Event[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadEventQueueByType_PagedCompletedEventHandler(object sender, ReadEventQueueByType_PagedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadEventQueueByType_PagedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadEventQueueByType_PagedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Event[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadEventQueue_INITCompletedEventHandler(object sender, ReadEventQueue_INITCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadEventQueue_INITCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadEventQueue_INITCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Event[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadEventQueuebySubscriberCompletedEventHandler(object sender, ReadEventQueuebySubscriberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadEventQueuebySubscriberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadEventQueuebySubscriberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Event[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertEventsCompletedEventHandler(object sender, InsertEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertEventsExCompletedEventHandler(object sender, InsertEventsExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertEventsExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertEventsExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public EventId[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventId[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateEventsCompletedEventHandler(object sender, UpdateEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AssignEventsCompletedEventHandler(object sender, AssignEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AssignEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AssignEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReAssignEventsCompletedEventHandler(object sender, ReAssignEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReAssignEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReAssignEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEventsByEventIdCompletedEventHandler(object sender, GetEventsByEventIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEventsByEventIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEventsByEventIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Event[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Event[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateEventProcessDateCompletedEventHandler(object sender, UpdateEventProcessDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEventProcessDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEventProcessDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] Results {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] Errors {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddSubscriberCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSubscribersCompletedEventHandler(object sender, GetSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subscriber[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subscriber[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetConfiguredListenersCompletedEventHandler(object sender, GetConfiguredListenersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfiguredListenersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfiguredListenersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591