//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.EcommSwitchPaymentProfile.Impl.PaymentProfileUpdate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QueuePPUpdateWebSvcSoap", Namespace="http://queueppupdate.godaddy.com/")]
    public partial class QueuePPUpdateWebSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetResourceProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueuePPUpdateWebSvc() {
            this.Url = global::Atlantis.Framework.EcommSwitchPaymentProfile.Impl.Properties.Settings.Default.Atlantis_Framework_EcommSwitchPaymentProfile_Impl_PaymentProfileUpdate_QueuePPUpdateWebSvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetResourceProfileCompletedEventHandler SetResourceProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://queueppupdate.godaddy.com/SetResourceProfile", RequestNamespace="http://queueppupdate.godaddy.com/", ResponseNamespace="http://queueppupdate.godaddy.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetResourceProfile(string sShopper, string sResourceId, string sNamespace, string sNamespaceType, int nPaymentProfileID, string sShopperNote, string sEnteredBy) {
            object[] results = this.Invoke("SetResourceProfile", new object[] {
                        sShopper,
                        sResourceId,
                        sNamespace,
                        sNamespaceType,
                        nPaymentProfileID,
                        sShopperNote,
                        sEnteredBy});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetResourceProfileAsync(string sShopper, string sResourceId, string sNamespace, string sNamespaceType, int nPaymentProfileID, string sShopperNote, string sEnteredBy) {
            this.SetResourceProfileAsync(sShopper, sResourceId, sNamespace, sNamespaceType, nPaymentProfileID, sShopperNote, sEnteredBy, null);
        }
        
        /// <remarks/>
        public void SetResourceProfileAsync(string sShopper, string sResourceId, string sNamespace, string sNamespaceType, int nPaymentProfileID, string sShopperNote, string sEnteredBy, object userState) {
            if ((this.SetResourceProfileOperationCompleted == null)) {
                this.SetResourceProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetResourceProfileOperationCompleted);
            }
            this.InvokeAsync("SetResourceProfile", new object[] {
                        sShopper,
                        sResourceId,
                        sNamespace,
                        sNamespaceType,
                        nPaymentProfileID,
                        sShopperNote,
                        sEnteredBy}, this.SetResourceProfileOperationCompleted, userState);
        }
        
        private void OnSetResourceProfileOperationCompleted(object arg) {
            if ((this.SetResourceProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetResourceProfileCompleted(this, new SetResourceProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetResourceProfileCompletedEventHandler(object sender, SetResourceProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetResourceProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetResourceProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591