//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis.Framework.MailApi.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlantis.Framework.MailApi.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:[{&quot;folder_num&quot;:&quot;821720&quot;,&quot;folder&quot;:&quot;INBOX&quot;,&quot;user_num&quot;:&quot;115748&quot;,&quot;uid_validity&quot;:&quot;1&quot;,&quot;uid_next&quot;:&quot;13096&quot;,&quot;exists_count&quot;:&quot;8442&quot;,&quot;seen_count&quot;:&quot;99&quot;,&quot;is_dirty&quot;:&quot;0&quot;,&quot;display_name&quot;:&quot;Inbox&quot;,&quot;system_folder&quot;:true},{&quot;folder_num&quot;:&quot;821721&quot;,&quot;folder&quot;:&quot;INBOX.Bulk Mail&quot;,&quot;user_num&quot;:&quot;115748&quot;,&quot;uid_validity&quot;:&quot;1&quot;,&quot;uid_next&quot;:&quot;3298&quot;,&quot;exists_count&quot;:&quot;3278&quot;,&quot;seen_count&quot;:&quot;10&quot;,&quot;is_dirty&quot;:&quot;0&quot;,&quot;display_name&quot;:&quot;Bulk Mail&quot;,&quot;system_folder&quot;:true},{&quot;folder_num&quot;:&quot;1254066&quot;,&quot;folder&quot;:&quot;INBOX.Deleted Items&quot;,&quot;user_num&quot;:&quot;115748&quot;,&quot;uid_validity&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidGetFolderListData {
            get {
                return ResourceManager.GetString("ValidGetFolderListData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;mail_headers&quot;:[{&quot;header_num&quot;:&quot;318877174&quot;,&quot;folder_num&quot;:&quot;821720&quot;,&quot;msg_uid&quot;:&quot;13095&quot;,&quot;filename&quot;:&quot;1393271690.981742.p3plgemini04-06.prod.phx.4060105024&quot;,&quot;to_fld&quot;:&quot;tester@qa-emailpod04.com&quot;,&quot;to_sort&quot;:&quot;tester qa-emailp&quot;,&quot;cc&quot;:&quot;&quot;,&quot;from_fld&quot;:&quot;Aaron Smentkowski &lt;asmenter15@gmail.com&gt;&quot;,&quot;from_sort&quot;:&quot;aaron smentkowsk&quot;,&quot;replyto&quot;:&quot;&quot;,&quot;internal_date&quot;:&quot;1393271690&quot;,&quot;msg_date&quot;:&quot;1393271683&quot;,&quot;subject&quot;:&quot;Test&quot;,&quot;subject_sort&quot;:&quot;test&quot;,&quot;msg_size&quot;:&quot;2144&quot;,&quot;modified_date&quot;:&quot;2014-02-24 12:55:00&quot;,&quot;priority&quot;:&quot;3&quot;,&quot;has_attachment&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidGetMessageListData {
            get {
                return ResourceManager.GetString("ValidGetMessageListData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;hash&quot;:&quot;3ec646ddd52660180db869372bf86c36&quot;,&quot;baseurl&quot;:&quot;mailapi04.secureserver.net:443&quot;,&quot;clienturl&quot;:&quot;https://mailapi04.secureserver.net/client.php?h=1a9605207194ceb558b40b1b9edc19ad&quot;},&quot;state&quot;:{&quot;app_key&quot;:&quot;tv2YfSzBx6zdjHAjIhW9mNe5&quot;}}.
        /// </summary>
        internal static string ValidLoginData {
            get {
                return ResourceManager.GetString("ValidLoginData", resourceCulture);
            }
        }
    }
}
